name: video_viewer
description: Multiplatform minimalist video viewer with spectacular user experience.
homepage: https://github.com/seel-channel/video_viewer
version: 1.2.6

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gesture_x_detector: ^1.0.0
  helpers: ^1.1.4
  http: ^0.13.3
  path_provider: ^2.0.2
  provider: ^5.0.0
  video_player: ^2.1.12
  volume_watcher: ^2.0.1
  wakelock: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

