name: video_viewer
description: Multiplatform minimalist video viewer with spectacular user experience.
homepage: https://github.com/seel-channel/video_viewer
version: 1.2.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.0
  helpers: ^1.1.0+2
  provider: ^5.0.0
  video_player: ^2.0.2
  universal_html: ^2.0.2
  gesture_x_detector: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
